name: 'ChimeOps'
description: 'Easily notify your Google Chat room from GitHub Actions with detailed pipeline status updates.'
author: 'Prajwal Adhikari'
inputs:
  name:
    description: 'The name of the job or step from your workflow.'
    required: true
  url:
    description: 'The Google Chat Webhook URL to which notifications will be sent.'
    required: true
  status:
    description: 'The current status of the job or step (e.g., success, failure, cancelled).'
    required: true
  custom_text:
    description: 'Optional: Add a custom message to include in the notification.'
    required: false
runs:
  using: 'node16'
  main: 'dist/main.js'
branding:
  icon: 'message-circle'
  color: 'yellow'
